//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listas0.Areas.AreaProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int empresa { get; set; }
        public int sucursal { get; set; }
        public long codigo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public int pk { get; set; }
        public string sexo { get; set; }
        public System.DateTime fe_nac { get; set; }
        public Nullable<int> CodCiudad { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public Nullable<int> Hijos { get; set; }
        public string Conyuge { get; set; }
        public Nullable<int> Documento { get; set; }
        public string cedula { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual DocumentosId DocumentosId { get; set; }
    }
}
