//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listas0.Areas.AreaProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public int empresa { get; set; }
        public int sucursal { get; set; }
        public long codigo { get; set; }
        public Nullable<int> ptovta { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
    }
}
